name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # Permite a execução manual do workflow pela aba Actions
  workflow_dispatch:

# Define permissões necessárias para o deploy no GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        # Usamos npm install. Se você faz push do package-lock.json, prefira usar "npm ci"
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: "deploy: atualizando GitHub Pages [skip ci]"
